wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1702878723.579777
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 2
      - 16
      - 19
      - 23
      4: 3.9.13
      5: 0.13.10
      6: 4.27.4
      8:
      - 5
batch_size:
  desc: null
  value: 128
data_path:
  desc: null
  value: /home/mrizhko/hn_miccai/data/
data_transforms:
  desc: null
  value:
    train: "Compose([\n  Rotate(always_apply=False, p=0.5, limit=(-30, 30), interpolation=1,\
      \ border_mode=4, value=None, mask_value=None, rotate_method='largest_box', crop_border=False),\n\
      \  RandomResizedCrop(always_apply=False, p=1.0, height=224, width=224, scale=(0.9,\
      \ 1.0), ratio=(1.0, 1.0), interpolation=1),\n  HorizontalFlip(always_apply=False,\
      \ p=0.5),\n  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406],\
      \ std=[0.229, 0.224, 0.225], max_pixel_value=255.0),\n  ToTensorV2(always_apply=True,\
      \ p=1.0, transpose_mask=False),\n], p=1.0, bbox_params=None, keypoint_params=None,\
      \ additional_targets={})"
    valid: "Compose([\n  Resize(always_apply=False, p=1, height=256, width=256, interpolation=1),\n\
      \  CenterCrop(always_apply=False, p=1.0, height=224, width=224),\n  Normalize(always_apply=False,\
      \ p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),\n\
      \  ToTensorV2(always_apply=True, p=1.0, transpose_mask=False),\n], p=1.0, bbox_params=None,\
      \ keypoint_params=None, additional_targets={})"
data_type:
  desc: null
  value: _seg_only
device:
  desc: null
  value: cuda
freeze:
  desc: null
  value: false
freeze_until:
  desc: null
  value: layer3
gamma:
  desc: null
  value: 0.85
loss:
  desc: null
  value: BCEAttention
lr:
  desc: null
  value: 0.001
model_name:
  desc: null
  value: resnet18
num_epochs:
  desc: null
  value: 30
pretrained:
  desc: null
  value: true
save_weights:
  desc: null
  value: true
threshold:
  desc: null
  value: 0.5
weight_decay:
  desc: null
  value: 0.1
weights_path:
  desc: null
  value: ''
